---
title: "Admissions MMI Interview data"
author: "Jacqueline Gutman"
date: 'Last updated: `r format(Sys.Date(), "%B %d, %Y") ` '
output:
  html_document:
    toc: yes
    toc_depth: '4'
  html_notebook:
    highlight: tango
    theme: cosmo
    toc: yes
    toc_depth: 4
---

```{r, message = FALSE}
library(tidyverse)
library(magrittr)
knitr::opts_chunk$set(message = FALSE, comment = "   ")

admissions1 <- "data/admissions_interviews_long_v1.csv" %>% read_csv()
```

```{r}
colnames(admissions1) %<>% tolower()

# -99 in column user_id and -9 in column faculty_user_id denote missing values
admissions1 %<>% mutate(user_id = replace(user_id, user_id == -99, NA_integer_),
    faculty_user_id = replace(faculty_user_id, faculty_user_id == -9, NA_integer_))
```

```{r}
admissions1 %<>% group_by(amcas_id, app_year, application_id) %>% 
  mutate(n = n()) %>% arrange(desc(n)) %>%
  unite(faculty_name, fac_last_name, fac_first_name, sep = ", ")
```

```{r}
interviewee_data <- admissions1 %>% select(app_year:amcas_id, interview_type, appl_person_id) %>% ungroup() %>% distinct() 

nrow(interviewee_data) == {admissions1 %>% group_by(application_id) %>% n_groups()}
```

```{r}
interviewee_data <- admissions1 %>%
  summarize(n_interviews = n(),
            min_rank = min(rank),
            max_rank = max(rank),
            median_rank = median(rank),
            mean_rank = mean(rank)) %>%
  left_join(interviewee_data, .)

spread_join_var <- function(wide_data, long_data, var_name) {
  wide_data <- long_data %>%
    select_(~application_id, ~interviewer_type, var_name) %>%
    mutate(interviewer_type = stringr::str_replace(interviewer_type, "Interviewer ", paste0(var_name, "_"))) %>%
    spread_("interviewer_type", value = var_name) %>%
    left_join(wide_data, .)
  return(wide_data)
}
```

```{r}
vars_to_spread <- c("rank", "faculty_name", "interview_id", "mmi_question_id")
interviewee_data %<>% reduce(vars_to_spread, spread_join_var, 
                        long_data = admissions1, .init = .)
```

```{r}
interviewee_data %>% write_csv("data/admissions_interviews_wide_v1.csv", na = "")
```

```{r}
screeners_path <- "data/screener_long.csv"
interviews_path <- "data/interview_long.csv"

spread_interviews <- function(path) {
  long_data <- read_csv(path)
  colnames(long_data) %<>% tolower()
  
  long_data %<>% 
    mutate(score_submission_date = lubridate::dmy_hms(score_submission_date, tz = "EST"),
           appl_person_id = replace(appl_person_id, appl_person_id == -9, NA_integer_))
}
```

```{r, message = FALSE}
parent_data <- "data/parent_guardian_long_v1.csv" %>% read_csv()

colnames(parent_data) %<>% tolower() %>% stringr::str_replace("_text", "")
```

```{r}
parent_data %<>% group_by(appl_person_id) %>% mutate(n_parents = n()) 

parent_data %<>% mutate(constcol = 1, rank = cumsum(constcol)) %>%
  filter(rank <= 4) %>% select(-constcol)

```

```{r}
parent_wide <- parent_data %>% select(appl_person_id, appl_year, n_parents) %>% ungroup() %>% distinct()

spread_join_var2 <- function(wide_data, long_data, var_name) {
  wide_data <- long_data %>%
    select_(~appl_person_id, ~rank, var_name) %>%
    mutate(rank = paste0(var_name, "_parent", rank)) %>%
    spread_("rank", value = var_name) %>%
    left_join(wide_data, .)
  return(wide_data)
}

vars_to_spread <- c("name", "occupation_desc", "occupation", "edu_level")
parent_wide %<>% reduce(vars_to_spread, spread_join_var2, 
                        long_data = parent_data, .init = .)
```

```{r}
parent_wide %>% write_csv("data/parent_guardian_wide_v1.csv", na = "")
```

