title: "Admissions dataset generation"
author: "Jacqueline Gutman, Suvam Paul"
date: 'Last updated: `r format(Sys.Date(), "%B %d, %Y") ` '
output:
  html_document:
    toc: yes
    toc_depth: '4'
  html_notebook:
    highlight: tango
    theme: cosmo
    toc: yes
    toc_depth: 4
---

```{r, message = FALSE}
library(tidyverse)
library(magrittr)
library(knitr)

opts_chunk$set(message = FALSE, warning = FALSE, comment = "   ",
               cache = TRUE, autodep = TRUE, cache.comments = FALSE)

#list.dirs("/Volumes/", full.names = TRUE, recursive = FALSE)
admissions_path <- "/Volumes/admissions" 
(raw_files <- list.files(admissions_path, full.names = TRUE))
```


```{r, message = FALSE}
extract_data <- function(file_list, pattern) {
  file_list %>%
    stringr::str_detect(regex(pattern, ignore_case = TRUE)) %>%
    which() %>%
    extract2(file_list, .) %>%
    read_csv() %>%
    set_colnames(tolower(colnames(.)))
}

applications <- raw_files %>%
  extract_data("/application") %>%
  select(-first_name, -last_name)


table(applications$appl_year)
#2006-2017

table(applications$application_status)
#Create accepted from Marticulated and Withdrawn after accepted! 


#create accepted
create_accepted_variable <- function(type) {
  switch(type, 
         "Accepted" = "Accepted",
         "Withdrawn after acceptance" = "Accepted",
         "Rescinded acceptance" = "Accepted", 
         "Matriculated" = "Accepted",
         "Other"
         )
}

applications <- applications %>% 
  mutate(accepted = purrr::map_chr(application_status, create_accepted_variable))
table(as.factor(applications$application_status), as.factor(applications$accepted))


#what does a repeated applications look like? 
app_repeated_count <- applications %>% 
  group_by(aamc_id) %>% 
  summarise(count_num = n()) %>% 
  filter(count_num > 1) %>% 
  arrange(aamc_id) %>% 
  ungroup()

applications_rep_info <- left_join(applications, app_repeated_count, by = "aamc_id")
applications_rep_info <- applications_rep_info %>% arrange(aamc_id, desc(appl_year))

applications_rep_info_14_17 <- applications_rep_info %>% filter(appl_year == 2014 | appl_year == 2015 | appl_year == 2016 | appl_year == 2017)

applications_rep_info_14_17_non_null_numcount <- applications_rep_info_14_17 %>% 
  filter(count_num == 2 | count_num == 3) %>% arrange(aamc_id)

applications_rep_info_14_17_non_null_numcount_accepted <- applications_rep_info_14_17_non_null_numcount %>% filter(application_status == "Accepted")

examine_repeates <- applications_rep_info_14_17_non_null_numcount %>% filter(aamc_id == 13791324) #deferred application for 2 years and then accepted offer (but unclear if ultimately enrolled?)
examine_repeates2 <- applications_rep_info_14_17_non_null_numcount %>% filter(aamc_id == 13995803) #rejected and the accepted!

##Thoughts
#How do I handle applications in multiple years? 
    #--combine year and aamc_id?


```


```{r}

applications %>%
  filter(program_name == "Regular M.D.") %>%
  group_by(appl_year, application_status) %>%
  summarize(count = n()) %>%
  spread(application_status, count, fill = 0)


#Types of aplication status

#Accepted
#Alternate list
#Deferred to future class
#Matriculated
#No action

```

```{r}
applications %>% 
  group_by(aamc_id) %>%
  summarize(n_times_applied = n_distinct(appl_year)) %>%
  group_by(n_times_applied) %>%
  summarize(n_applicants = n())
```


```{r, mcat_old}
mcat_old <- raw_files %>% 
  extract_data("/mcat") %>%
  set_colnames(stringr::str_replace(colnames(.), "_p$", "_percentile"))


#prase months from string date
parse_betweeen_first_second_dash <- function(stringval) {
  loc <- stringr::str_locate_all(stringval, "-")
  stringr::str_sub(stringval, (sapply(loc, "[[", 1)) + 1, (sapply(loc, "[[", 2)) - 1)
}

parse_before_first_dash <- function(stringval) {
  loc <- stringr::str_locate(stringval, "-")
  stringr::str_sub(stringval, 1, loc[, "start"] -1)
}

parse_after_second_dash <- function(stringval) {
  loc <- stringr::str_locate_all(stringval, "-")
  stringr::str_sub(stringval, unlist((lapply(loc, "[[", 2))) + 1)
}

rename_month_to_number <- function(type) {
 switch(type,
        "JAN" = "1",
        "FEB" = "2",
        "MAR" = "3",
        "APR" = "4",
        "MAY" = "5",
        "JUN" = "6",
        "JUL" = "7",
        "AUG" = "8",
        "SEP" = "9",
        "OCT" = "10",
        "NOV" = "11",
        "DEC" = "12",
        "Not available")
}


#create date variable
mcat_old <- mcat_old %>% 
  mutate(month_letter = parse_betweeen_first_second_dash(test_date), 
         month_number = purrr::map(month_letter, rename_month_to_number),
         date_number = parse_before_first_dash(test_date),
         year_number= parse_after_second_dash(test_date),
         date = lubridate::mdy(paste(month_number, date_number, year_number, sep = "/")))




#keep only distinct combinations of date and aamc_id
mcat_old2 <- mcat_old %>% 
  distinct(aamc_id, date, .keep_all = TRUE)


#rank mcat by date taken
mcat_old2 <- mcat_old2 %>% 
  group_by(aamc_id) %>% 
  mutate(rank = rank(desc(date), ties = "min")) %>% 
  arrange(aamc_id, rank) %>% 
  ungroup()


#test for correct ranking of multiple mcat score for one person
mcat_old2_examine <- mcat_old2 %>% 
  filter(aamc_id == 10038666) #has multiple mcat scores


#keep the latest mcat score - but problem if they took the new mcat, then not latest score
final_mcat_old <- mcat_old2 %>% 
  filter(rank == 1) 



```


```{r, mcat_new}
mcat_new <- raw_files %>% 
  extract_data("new_mcat")

head(mcat_new)

table(as.factor(mcat_new$appl_year))

names(mcat_new)

mcat_new <- mcat_new %>% 
  mutate(month_letter = parse_betweeen_first_second_dash(new_mcat_test_date), 
         month_number = purrr::map(month_letter, rename_month_to_number),
         date_number = parse_before_first_dash(new_mcat_test_date),
         year_number= parse_after_second_dash(new_mcat_test_date),
         date = lubridate::mdy(paste(month_number, date_number, year_number, sep = "/")))


mcat_new2 <- mcat_new %>% 
  distinct(aamc_id, date, .keep_all = TRUE)

mcat_new2 <- mcat_new2 %>% 
  group_by(aamc_id) %>% 
  mutate(rank = rank(desc(date), ties = "min")) %>% 
  arrange(aamc_id, rank) %>% 
  ungroup()


#test that ranks are done the same way
mcat_new2_examine <- mcat_new2 %>% filter(aamc_id == 11012697) #has multiple mcat scores


final_mcat_new <- mcat_new2 %>% 
  filter(rank == 1) %>% 
  select(-(month_letter:year_number))


```


```{r, further_analysis_mcat_old_new}
#I have the latest old mcat for each person and the latest new mact for each person

#what if someone took an old mcat and new mcat? 

final_mcat_old <- final_mcat_old %>% mutate(mcat_type = "old")
final_mcat_new <- final_mcat_new %>% mutate(mcat_type = "new")

sub_mcat_old <- final_mcat_old %>% dplyr::select(aamc_id, mcat_type, rank, appl_year)
sub_mcat_new <- final_mcat_new %>% dplyr::select(aamc_id, mcat_type, rank, appl_year)

sub_mcat_both <- rbind(sub_mcat_old, sub_mcat_new)

sub_mcat_both <- sub_mcat_both %>% arrange(aamc_id)

sub_mcat_both_count <- sub_mcat_both %>% 
  group_by(aamc_id, mcat_type) %>% 
  summarise(count = n()) %>% 
  arrange(aamc_id)

table(as.factor(sub_mcat_both_count$count))
table(as.factor(sub_mcat_both_count$count), sub_mcat_both_count$mcat_type)

sub_mcat_both_count_wide <- sub_mcat_both_count %>% 
  spread(mcat_type, count) 

sub_mcat_both_count_wide <- sub_mcat_both_count_wide %>%
  filter(new ==1 & old == 1)

dim(sub_mcat_both_count_wide) 

#2518 applicants has both old and new mcats


#compare the dates of the old and new mcats, and only take the the ones that has a latest, update the old and new mcat datases accordingly

old_mcat_dates <- left_join(sub_mcat_both_count_wide, final_mcat_old, by = "aamc_id") %>% 
  dplyr::select(aamc_id, date) %>% 
  rename(latest_old_mcat_date = date)

dim(old_mcat_dates)

new_mcat_dates <- left_join(sub_mcat_both_count_wide, final_mcat_new, by = "aamc_id") %>% 
  dplyr::select(aamc_id, date) %>% 
  rename(latest_new_mcat_date = date)

dim(new_mcat_dates)
names(new_mcat_dates)

mcat_score_dates <- left_join(old_mcat_dates, new_mcat_dates) %>% 
  mutate(old_mcat_latest = as.numeric(latest_old_mcat_date > latest_new_mcat_date), 
         new_mcat_latest = as.numeric(latest_old_mcat_date < latest_new_mcat_date))

table(as.factor(mcat_score_dates$old_mcat_latest), as.factor(mcat_score_dates$new_mcat_latest))


#For everyone who took both mcats, their latest mcat is the new one

#Therefore remove them from the old mcat dataset who has a new mcat score


#write this file for old mcat scores
final_mcat_old2 <- left_join(final_mcat_old, mcat_score_dates) %>% 
  filter(is.na(new_mcat_latest)) %>% 
  dplyr::select(-(month_letter:year_number)) %>% 
  dplyr::select(-(mcat_type:new_mcat_latest)) %>% 
  dplyr::select(-appl_year)

#write this file for new mcat score
final_mcat_new <- final_mcat_new %>% 
  dplyr::select(-appl_year) %>% 
  dplyr::select(-mcat_type)

names(final_mcat_new)
```


```{r, message = FALSE}

# mmi_full <- raw_files %>% 
#   extract_data("/mmi.csv")

```


```{r, message = FALSE}
# # get percent missing by column by year
# mmi_full %>%
#   group_by(app_year) %>%
#   summarize_all(funs(mean(is.na(.))))
# 
# 
# # all rows and applicants included
# mmi_full %>%
#   group_by(app_year) %>%
#   summarize(n = n(),
#             n_applicants = n_distinct(appl_person_id))
# 
# # non-null rows and applicants only
# mmi_full %>% 
#   group_by(app_year) %>% 
#   filter(!is.na(rank) | !is.na(interviewer_type)) %>%
#   summarize(n = n(), n_applicants = n_distinct(appl_person_id))
# 
# 
# #mmi dataset that's non-null and applicants only
# mmi_nonnull_applicants <- mmi_full %>% 
#     filter(!is.na(rank) | !is.na(interviewer_type)) %>% 
#   arrange(aamc_id)
# 
# 
# #test
# mmi_nonnull_examine <- mmi_full %>% filter(aamc_id == 13791324)
# 
# mmi_nonnull_examine_2 <- mmi_full %>% filter(aamc_id == 13995803)


```


```{r, mmi}

#new mmi pull
mmi_pull_2 <- raw_files %>% 
  extract_data("/MMI_Scores_Admission")

names(mmi_pull_2)[2] <- "aamc_id"

mmi_pull_2 %>%
  group_by(app_year) %>%
  summarize_all(funs(mean(is.na(.))))

table(mmi_pull_2$app_year)
#MMI data 2013-2017 app year

#test for matching of info with application data
mmi_examine <- mmi_pull_2 %>% filter(aamc_id == 13791324) #deferred application for 2 years and then accepted

mmi_examine_2 <- mmi_pull_2 %>% filter(aamc_id == 13995803) #rejected and the accepted!

#write this dataset for final mmi dataset
```




```{r, committee}
committee <- raw_files %>% 
  extract_data("/Committee")

names(committee)

table(as.factor(committee$app_year))
#2012-2017 app year, committee decision for all applicants, regular and non interviews 

committee <- committee %>%
  arrange(aamc_id) 

committee %>% 
  group_by(aamc_id) %>%
  summarize(n_times_applied = n_distinct(app_year)) %>%
  group_by(n_times_applied) %>%
  summarize(n_applicants = n())

examine_repeates_committe <- committee %>% filter(aamc_id == 13995803) #rejected and the accepted!
examine_repeates_committe2 <- committee %>% filter(aamc_id == 13791324) #deferred application for 2 years and then accepted

table(as.factor(committee$activity_text), as.factor(committee$faculty_activity))
table(as.factor(committee$activity_text), as.factor(committee$committee_chair_score_text))
table(as.factor(committee$committee_chair_score_text), as.factor(committee$faculty_activity))
table(as.factor(committee$activity_text), as.factor(committee$app_year))

examine_hold <- committee %>% filter(activity_text == "Hold" & !is.na(committee_chair_score_text)) 

#No committee data prior to 2013
```




```{r, gpa}
gpa <- raw_files %>% 
  extract_data("/GPA_Scores")


names(gpa)
table(gpa$appl_year)


#Question on data quality: are there any unnecessary duplicates? 
gpa_examine <- gpa %>% filter(aamc_id == 13995803) #rejected and the accepted!
#Yes!

gpa_final <- gpa %>% 
  distinct(aamc_id, aca_status_desc, .keep_all = TRUE) 
#write this paper for final dataset

#test
gpa_examine2 <- gpa_final %>% filter(aamc_id == 13995803) #rejected and the accepted!

names(gpa_final)

#Question's for model building
#What's the gpa at time of application? 
#What's the gpa at from their primary institution? 

```


```{r, ethnicity}

ethnicity <- raw_files %>% 
  extract_data("/Ethnicity")

eth_examine <- ethnicity %>% filter(aamc_id == 13995803) #rejected and then accepted

ethnicity_final <- ethnicity %>% 
  distinct(aamc_id, ethnicity, .keep_all = TRUE) %>% 
  dplyr::select(-appl_year)
#write this for the final dataset

eth_examine2 <- ethnicity_final %>% filter(aamc_id == 13995803) #rejected and then accepted
```


```{r, race}
race <- raw_files %>% 
  extract_data("/Race")

race_examine <- race %>% filter(aamc_id == 13791324) #deferred twice
race_examine2 <- race %>% filter(aamc_id == 13995803) #rejected and then accepted

race_final <- race %>% 
  distinct(aamc_id, race, .keep_all = TRUE) %>% dplyr::select(-appl_year)
#write this file for final dataset

race_examine3 <- race_final %>% filter(aamc_id == 13791324) #deferred twice
```

```{r, school}

schools <- raw_files %>% 
  extract_data("/School.csv")

names(schools)

#Question on data quality: are there any unnecessary duplicates? 
schools_examine <- schools %>% filter(aamc_id == 13995803) #rejected and the accepted!
schools_examine <- schools %>% filter(aamc_id == 13791324) #deferred twice

#Yes!


#create a distinct dataset that's the unique combincation of id, name of school, and type of schools
schools_final <- schools %>% 
  distinct(aamc_id, mod_school_desc, program_type_desc, .keep_all = TRUE) %>% 
  dplyr::select(-appl_year)
#write this datatset for final dataset

#test
schools_examine2 <- schools_final %>% filter(aamc_id == 13995803) #rejected and the accepted!
schools_examine3 <- schools_final %>% filter(aamc_id == 13791324) #deferred twice


#What is the student's primary undergraduate institution
#Has a master's degree? 
```

