---
title: "Admissions internal process data"
author: "Jacqueline Gutman, Suvam Paul"
date: 'Last updated: `r format(Sys.Date(), "%B %d, %Y") ` '
output:
  html_document:
    toc: yes
    toc_depth: '4'
  html_notebook:
    highlight: tango
    theme: cosmo
    toc: yes
    toc_depth: 4
---

```{r, message = FALSE}
library(tidyverse)
library(magrittr)
library(knitr)
library(stringr)
library(readxl)

opts_chunk$set(message = FALSE, warning = FALSE, comment = "   ",
               cache = TRUE, autodep = TRUE, cache.comments = FALSE)

parent_path <- "/Volumes/IIME/EDS/data/admissions/data_documentation_from_lisa_admissions"
#parent_path <- "/Volumes/data_documentation_from_lisa_admissions"
admissions_path <- paste(parent_path, "Data", sep = "/")
(raw_files <- list.files(admissions_path, full.names = TRUE))
```

```{r, warning = FALSE, eval = FALSE}
raw_files %>% 
  str_detect(regex("/\\d{4} all applicants", ignore_case = TRUE)) %>%
  which() %>% extract(raw_files, .) %>%
  purrr::map(function(path) readxl::read_excel(path)) %>%
  set_names(2013:2016) -> applicants_data

# Make sure the column names in the 4 dataframes are all identical
applicants_data %>% map(colnames) %>% {all.equal(.$`2013`, .$`2014`)}
applicants_data %>% map(colnames) %>% {all.equal(.$`2013`, .$`2015`)}
applicants_data %>% map(colnames) %>% {all.equal(.$`2013`, .$`2016`)}

# Extract the data type for each column in each data frame
coltypes_df <- applicants_data %>% 
  at_depth(2, class) %>% 
  at_depth(2, extract(1)) %>% 
  as_data_frame() %>% 
  unnest()

single_value <- function(a) {
  length(unique(a)) == 1
}

coltypes_df <- coltypes_df %>%
  mutate_all(funs(str_replace_all(., 
        c("character" = "text", "POSIXct" = "date")))) %>%
  invoke_rows(c, ., .collate = "list", .to = "coltypes") %>%
  mutate(colname = colnames(applicants_data[[1]]),
         agreement = map_lgl(coltypes, single_value),
         coltypes_factor = map(coltypes, function(.x) {
           factor(.x, levels = c("numeric", "text", "date"), ordered = TRUE)})) %>%
  mutate(primary_coltype = map_chr(coltypes_factor, 
            function(.x) {as.character(max(.x))})) 

documentation_path <- paste(parent_path, "Documentation", "coltypes_admissions.csv", sep = "/")
coltypes_df %>% select(colname, primary_coltype) %>% write_csv(documentation_path)
```


```{r}
documentation_path <- paste(parent_path, "Documentation", "coltypes_admissions.csv", sep = "/")
coltypes_df <- read_csv(documentation_path)

# raw_files <- list.files("~/Desktop/Box Sync/Data for Admissions/", full.names = TRUE)
```


```{r, message = FALSE, warning = FALSE}
raw_files %>% 
  str_detect(regex("/\\d{4} all applicants", ignore_case = TRUE)) %>%
  which() %>% extract(raw_files, .) %>%
  map(function(path) read_excel(path, col_types = coltypes_df$primary_coltype)) %>%
  map(function(df) set_names(df, str_replace_all(colnames(df), " ", "_"))) %>%
  map(function(df) set_names(df, tolower(colnames(df)))) %>%
  map(function(df) rename(df, aamc_id = amcas_id)) %>%
  set_names(2013:2016) -> applicants_data

applicants_all_years <- bind_rows(applicants_data)
applicants_2013 <- applicants_data$`2013`
applicants_2014 <- applicants_data$`2014`
applicants_2015 <- applicants_data$`2015`
applicants_2016 <- applicants_data$`2016`

colnames(applicants_all_years)

id_columns <- c("amcas_id", "app_year")
tracking_columns <- c("appl_submit_date",
                      "appl_complete_date",
                      "screening_complete_date",
                      "interview_invite_date",
                      "interview_schedule_date",
                      "interview_day",
                      "interview_complete_date",
                      "committee_date",
                      "offer_date",
                      "accept_date")
```

```{r}
filter_applications <- . %>%
  # filter out M.D./Ph.D. applicants, special programs (i.e. linkages), and 
  # deferred applicants from previous years
  filter(appl_type_desc %in% c("Regular M.D.", "Combined  Medical Degree/Graduate")) %>%
  filter(!str_detect(status, "M\\w{2}")) %>%
  filter(!is.na(appl_submit_date) & !is.na(appl_complete_date))

split_screener_score <- . %>% 
  mutate(screener_a_b = recode(scr_dec, 
          `2` = "1_1", `3` = "1_2", `4` = "4", `5` = "2_3", `6` = "3_3"),
        screener_a_b = if_else(scr_dec == 4, 
          if_else(screener_sd == 0, "2_2", "1_3"), screener_a_b)) %>%
  separate(screener_a_b, c("screener_a", "screener_b"))

tally_screened_by_score <- . %>%
  {table(screener_a = .$screener_a, screener_b = .$screener_b)} %>% 
  as.data.frame() %>%
  filter(Freq > 0)

filter_pile_by <- function(data, pile_name, filter_name, superset_name) {
  
  filter_condition <- lazyeval::interp(~ map(data_col, 
      function(df) filter(df, !is.na(filter_col))), 
    data_col = as.name(superset_name), 
    filter_col = as.name(filter_name))
  
  count_filtered <- lazyeval::interp(~ map_int(filtered_pile, nrow),
    filtered_pile = as.name(pile_name))
  
  count_name <- paste0("n_", pile_name)
  
  data %>%
    mutate_(.dots = set_names( list(filter_condition), pile_name)) %>%
    mutate_(.dots = set_names( list(count_filtered), count_name))
}

n_applications_by_phase <- function(applications) {
  applications %>%
    mutate(n_total_applications = map_int(total_applications, nrow),
           screening_eligible = map(total_applications, filter_applications),
           n_screening_eligible = map_int(screening_eligible, nrow)) %>%
    filter_pile_by(pile_name = "faculty_screened", 
                   filter_name = "scr_dec",
                   superset_name = "screening_eligible") %>%
    mutate(faculty_screened = map(faculty_screened, split_screener_score)) %>%
    mutate(n_invited_from_screening = map_int(faculty_screened, function(df)
              sum(df$scr_dec == 2)),
           n_held_from_screening = map_int(faculty_screened, function(df)
              sum((df$scr_dec == 3) | (df$scr_dec == 4))),
           n_rejected_from_screening = map_int(faculty_screened, function(df)
              sum(df$scr_dec >=5))) %>%
    filter_pile_by(pile_name = "invited_for_interview", 
                   filter_name = "interview_invite_date",
                   superset_name = "faculty_screened") %>%
    filter_pile_by(pile_name = "interviewed", 
                   filter_name = "interview_day",
                   superset_name = "invited_for_interview") %>%
    filter_pile_by(pile_name = "committee_reviewed", 
                   filter_name = "committee_date",
                   superset_name = "interviewed") %>%
    mutate(n_fast_track = map_int(committee_reviewed, function(df)
              sum(df$committee_score == "Fast Track")),
           n_a_plus = map_int(committee_reviewed, function(df)
              sum(df$committee_score == "A+")),
           n_pwl = map_int(committee_reviewed, function(df)
              sum(df$committee_score == "PWL")),
           n_waitlist = map_int(committee_reviewed, function(df)
              sum(df$committee_score == "WL")),
           n_rejected_from_committee = map_int(committee_reviewed, function(df)
              sum(df$committee_score == "RJ"))) %>%
    filter_pile_by(pile_name = "offered_admission", 
                   filter_name = "offer_date",
                   superset_name = "interviewed") ->
    screened_applications
}

applicants_all_years %>% 
  group_by(app_year) %>% 
  nest(.key = total_applications) %>%
  n_applications_by_phase() -> nested_applicants

nested_applicants %>%
  select(app_year, starts_with("n_")) %>%
  write_csv("application_phase_counts_by_year.csv")
```

```{r}
nested_applicants %>% 
  select(app_year, faculty_screened) %>% 
  unnest() %>% 
  mutate(invited_interview = !is.na(interview_invite_date),
         interviewed = !is.na(interview_day)) -> temp_screened

with(temp_screened, table(scr_dec, invited_interview))
with(temp_screened, table(scr_dec, interviewed))

temp_screened %>% 
  filter(scr_dec >=5, invited_interview) %>%
  select(aamc_id, status, scr_dec, total_gpa, cu_sci_gpa, gender, disadvantaged_ind, urm, ses, special_interest) %>%
  {table(.$scr_dec, .$special_interest)}

ind <- temp_screened %>% filter(aamc_id == 13284807)
temp_screened %>% 
  filter(scr_dec == 2, !invited_interview) %>%
  select(aamc_id, app_year, status, screening_complete_date) -> screening_reject_2

temp_screened %>% filter(aamc_id %in% screening_reject_2$aamc_id)
```

```{r}
nested_applicants %>% 
  select(committee_reviewed) %>% 
  unnest() %>% 
  mutate(offered_admission = !is.na(offer_date),
         matriculated = ((status == "MM") | (status == "MD"))) -> temp_committee

with(temp_committee, table(committee_score, offered_admission))
with(temp_committee, table(committee_score, matriculated))
```


```{r}
a2016 <- nested_applicants %>% 
  filter(app_year == 2016) %>% 
  select(faculty_screened) %>% 
  unnest()

a2016 %>% 
  split_screener_score() %>% 
  tally_screened_by_score()
```


```{r}
application_status_by_month <- . %>% 
  filter_applications() %>% 
  extract(tracking_columns) %>%
  gather(event, date, na.rm = TRUE) %>% 
  mutate(month = lubridate::month(date),
         year = lubridate::year(date)) %>%
  group_by(event, year, month) %>%
  summarize(count = n()) %>%
  spread(event, count, fill = 0) %>%
  select(month, year, one_of(tracking_columns))

applicants_2016 %>% application_status_by_month
```


```{r}
screener_codes <- expand.grid(screener_a = 1:3, screener_b = 1:3) %>%
  mutate(scr_dec = screener_a + screener_b,
         screener_sd = purrr::map2_dbl(screener_a, screener_b, 
                          function(a, b) sd( c(a, b) )
                       )) %>% 
  arrange(scr_dec, screener_sd) %>%
  distinct(scr_dec, screener_sd, .keep_all = TRUE)

screener_codes
```

```{r}

```

