---
title: "Create clean version of GPA dataset"
author: "Suvam Paul"
date: 'Last updated: `r format(Sys.Date(), "%B %d, %Y") ` '
output:
  html_document:
    toc: yes
    toc_depth: '4'
  html_notebook:
    highlight: tango
    theme: cosmo
    toc: yes
    toc_depth: 4
---

# Setup
## Load packages
## Read in database credentials and open connection

```{r setup, message=FALSE, echo = FALSE, purl = FALSE}
knitr::read_chunk("setup_notebook.R")
```

```{r setup_notebook, purl = FALSE}

```

```{r echo = FALSE, purl = FALSE}
print_loaded_pkgs()
```

## GPA cleaning


```{r check_tables_in_database}

table_names <- dbListTables(edu_db_con) %>% print()

```


```{r get_gpa_dataset}

#get data
gpa <- dbUtilities::put_tbl_to_memory(edu_db_con, "deidentified$clean$gpa")

```


```{r ensure_has_14_17_data}

library(assertr)

gpa %>% 
  assert(within_bounds(2014, 2017), appl_year, success_fun = success_logical, error_fun = error_stop) 


```



```{r drop_high_school}
#education levels
table(gpa$aca_status_desc)

#drop high school grades
gpa %>% filter(aca_status_desc != "High School") -> gpa
```





```{r simple_functions}
#simple utility funcions - missingness

#functions
is_science_gpa_missing <- . %>% 
  use_series(bcpm_gpa) %>% 
  is.na() %>% 
  sum()


missing_science_gpa_year <- . %>% 
  group_by(appl_year) %>% 
  summarise(count = sum(is.na(bcpm_gpa)))

```



```{r missing}
#total missing
gpa %>% is_science_gpa_missing()
#7187


#missing breakdown by application year
gpa %>% missing_science_gpa_year()
```



```{r postbacs}

#1 
#Any postback missing science gpa
gpa %>% filter(is.na(bcpm_gpa) & aca_status_desc == "Postbaccalaureate Undergraduate") 


#If postback then science gpa is total gpa
gpa %>% 
  mutate(bcpm_gpa = ifelse((is.na(bcpm_gpa) & aca_status_desc == "Postbaccalaureate Undergraduate"), total_gpa, bcpm_gpa)) -> gpa
  

gpa %>% is_science_gpa_missing()
#6911



#2
#Are there people still missing science gpa if postbac - total or science? 
gpa %>% 
  filter(aca_status_desc == "Postbaccalaureate Undergraduate" & is.na(bcpm_gpa) & is.na(total_gpa)) %>% 
  dim()

#Are these people also missing all science gpa's?
gpa %>% 
  filter(aca_status_desc == "Postbaccalaureate Undergraduate" & is.na(bcpm_gpa) & is.na(total_gpa)) %>% 
  semi_join(gpa, ., by = "study_id") %>% 
  group_by(study_id) %>% 
  dplyr::mutate(missing = all(is.na(bcpm_gpa))) %>% 
  use_series(missing) %>% 
  sum()
  

#Filter out the rows for these postbac people
gpa %>%
  filter(aca_status_desc == "Postbaccalaureate Undergraduate" & is.na(bcpm_gpa) & is.na(total_gpa)) %>%
  dplyr::setdiff(gpa, .) -> gpa


gpa %>% is_science_gpa_missing()
#6800

gpa %>% missing_science_gpa_year()

#3 
#... 



```



```{r}
#is anybody missing any science gpa

gpa %>% 
  group_by(study_id) %>% 
  dplyr::mutate(missing = all(is.na(bcpm_gpa))) %>% 
  use_series(missing) %>% 
  sum()


gpa %>% 
  group_by(study_id) %>% 
  dplyr::mutate(missing = all(is.na(bcpm_gpa))) %>% 
  arrange(study_id, missing) %>% 
  filter(missing == TRUE)
  
  
gpa %>% filter(study_id == "01044f52e372b0c5e83d6719fe7fe92e")

```

