---
title: "Deidentify raw tables in database"
subtitle: "Upload deidentified files to db"
author: "Jacqueline Gutman, Suvam Paul"
date: 'Last updated: `r format(Sys.Date(), "%B %d, %Y") ` '
output:
  html_document:
    toc: yes
    toc_depth: '4'
  html_notebook:
    highlight: tango
    theme: cosmo
    toc: yes
    toc_depth: 4

---

# Setup

## Load packages

```{r, message=FALSE}
library(tidyverse)
library(RMySQL)
library(yaml)
library(knitr)
library(stringr)
library(magrittr)
library(lubridate)

sessionInfo() %>%
  use_series(otherPkgs) %>%
  map_chr(function(pkg) paste(pkg$Package, pkg$Version)) %>%
  cat(sep = "\n")

opts_chunk$set(message = FALSE, warning = FALSE, comment = "   ",
            cache = TRUE, autodep = TRUE, cache.comments = FALSE)

```

## Read in database credentials and open connection

```{r}
devtools::install("dbUtilities", dependencies = FALSE, quiet = TRUE)
library(dbUtilities)
```


```{r, echo=FALSE}
credentials_path <- "/Volumes/IIME/EDS/data/admissions/db_credentials/"
edu_db_con <- get_mysql_conn(credentials_path, group = "edu_db_owner")
```

# Admissions applicants datasets: 2013-2017

## Read in all_applicants tables from database

```{r}
table_names <- dbListTables(edu_db_con) %>% print()

edu_db_con %>%
  get_tbls_by_pattern("^hashed\\Wraw\\W\\d{4}_all_applicants") %>%
  set_names(2013:2017) -> applicants_data
```

```{r}
# filter out irrelevant and identifying columns
applicants_data %<>% 
  keep_cols_from_list("cols_to_keep_admissions.yaml")
```

```{r}
# check that all columns and coltypes are the same for all application years
applicants_data %>% 
  at_depth(2, typeof) -> coltypes

coltypes %>% 
  as_data_frame() %>% 
  mutate_all(flatten_chr) -> coltypes_df

coltypes %>% 
  map(names) %>% 
  as_data_frame() %>% 
  all_equal_across_row()

coltypes %>% 
  extract2(1) %>% 
  names() %>%
  mutate(coltypes_df, colname = .) %>%
  select(-colname) %>% 
  all_equal_across_row()
```

```{r}
applicants_all_years <- bind_rows(applicants_data)
colnames(applicants_all_years)
```

```{r}
# write deidentified data to file
deidentified_output <- "/Volumes/IIME/EDS/data/admissions/data_for_itai/"

applicants_all_years %>%
 write_to_file(deidentified_output, "admissions_all_applicants_deidentified.csv")
```

```{r}
names(applicants_data) %>%
  add_tbl_prefix("deidentified", "raw") %>%
  paste("all_applicants", sep = "_") ->
  tbl_names

applicants_data %<>% set_names(tbl_names)
applicants_data %>% write_to_database(edu_db_con)
```

# Raw features from eduDW tables

## Ethnicity

```{r, ethnicity, echo=FALSE}

# deidentified raw
edu_db_con %>%
  deidentify_hashed(tbl_name = "ethnicity", 
      "aamc_id", "appl_person_id") ->
  ethnicity_raw_deid

ethnicity_raw_deid %>%
  write_to_database_single(edu_db_con, 
        add_tbl_prefix("ethnicity", status = "raw"))

# deidentified clean
edu_db_con %>%
  clean_deidentified(tbl_name = "ethnicity") ->
  ethnicity_clean_deid

ethnicity_clean_deid %>%
  write_to_database_single(edu_db_con, 
        add_tbl_prefix("ethnicity", status = "clean"))

# write data to file
ethnicity_raw_deid %>%
 write_to_file(deidentified_output, "ethnicity_raw_deidentified.csv")  
  
ethnicity_clean_deid %>%
 write_to_file(deidentified_output, "ethnicity_clean_deidentified.csv")  

```

## Race

```{r, race, echo=FALSE}

# deidentfied raw
edu_db_con %>%
  deidentify_hashed(tbl_name = "race",
      "aamc_id", "appl_person_id") ->
  race_raw_deid 

race_raw_deid %>%
  write_to_database_single(edu_db_con, 
        add_tbl_prefix("race", status = "raw"))

# deidentified clean
edu_db_con %>%
  clean_deidentified(tbl_name = "race") ->
  race_clean_deid

race_clean_deid %>%
  write_to_database_single(edu_db_con, 
        add_tbl_prefix("race", status = "clean"))

# write data to file
race_raw_deid %>%
 write_to_file(deidentified_output, "race_raw_deidentified.csv")  
  
race_clean_deid %>%
 write_to_file(deidentified_output, "race_clean_deidentified.csv") 
```

## Schools

```{r, schools, echo=FALSE}

# deidentfied raw
edu_db_con %>%
  deidentify_hashed(tbl_name = "school",
      "aamc_id", "appl_person_id") ->
  schools_raw_deid 
  
schools_raw_deid %>%
  write_to_database_single(edu_db_con, 
        add_tbl_prefix("school", status = "raw"))

# deidentified clean
edu_db_con %>%
  clean_deidentified(tbl_name = "school") ->
  schools_clean_deid

schools_clean_deid %>%
  write_to_database_single(edu_db_con, 
        add_tbl_prefix("school", status = "clean"))

# write data to file
schools_raw_deid %>%
 write_to_file(deidentified_output, "schools_raw_deidentified.csv")  
  
schools_clean_deid %>%
 write_to_file(deidentified_output, "schools_clean_deidentified.csv") 
```

## GPA

```{r, gpa, echo=FALSE}

# deidentfied raw
edu_db_con %>%
  deidentify_hashed(tbl_name = "gpa",
      "aamc_id", "appl_person_id") ->
  gpa_raw_deid 

gpa_raw_deid %>%
  write_to_database_single(edu_db_con, 
        add_tbl_prefix("gpa", status = "raw"))

# deidentified clean
edu_db_con %>%
  clean_deidentified(tbl_name = "gpa") ->
  gpa_clean_deid

gpa_clean_deid %>%
  write_to_database_single(edu_db_con, 
        add_tbl_prefix("gpa", status = "clean"))

# write data to file
gpa_raw_deid %>%
 write_to_file(deidentified_output, "gpa_raw_deidentified.csv")  
  
gpa_clean_deid %>%
 write_to_file(deidentified_output, "gpa_clean_deidentified.csv")
```

## MMI

```{r, mmi, echo = FALSE}

# deidentfied raw
edu_db_con %>%
  deidentify_hashed(tbl_name = "mmi_scores",
      "amcas_id", "appl_person_id", "application_id",
      "fac_last_name", "fac_first_name", "comment", 
      "avg", "stdev", "conflict", "interview_id", 
      "scenario") %>%
  rename(appl_year = app_year) ->
  mmi_raw_deid 

mmi_raw_deid %>%
  write_to_database_single(edu_db_con, 
        add_tbl_prefix("mmi_scores", status = "raw"))

# deidentfied clean
edu_db_con %>%
  clean_deidentified(tbl_name = "mmi_scores",
                     min_year = 2014) %>%
  select(-mmi_question_id, -code) %>%
  mutate(interviewer_type = str_replace(interviewer_type, "Interviewer ", "")) %>%
  mutate(interviewer_type = as.integer(interviewer_type)) ->
  mmi_clean_deid

mmi_clean_deid %>%
  write_to_database_single(edu_db_con, 
        add_tbl_prefix("mmi_scores", status = "clean"))

# write data to file
mmi_raw_deid %>%
 write_to_file(deidentified_output, "mmi_raw_deidentified.csv")  

mmi_clean_deid %>%
 write_to_file(deidentified_output, "mmi_clean_deidentified.csv")
```

## MCAT: OLD

```{r, mcat_old, echo=FALSE}

# deidentfied raw
edu_db_con %>%
  deidentify_hashed(tbl_name = "old_mcat",
      "aamc_id", "appl_person_id") ->
  old_mcat_raw_deid 

old_mcat_raw_deid %>%
  write_to_database_single(edu_db_con, 
        add_tbl_prefix("old_mcat", status = "raw"))

# deidentfied clean
edu_db_con %>%
  clean_deidentified(tbl_name = "old_mcat") ->
  old_mcat_clean_deid

old_mcat_clean_deid %>%
  write_to_database_single(edu_db_con, 
        add_tbl_prefix("old_mcat", status = "clean"))

# write data to file
old_mcat_raw_deid %>%
 write_to_file(deidentified_output, "old_mcat_raw_deidentified.csv")  
  
old_mcat_clean_deid %>%
 write_to_file(deidentified_output, "old_mcat_clean_deidentified.csv")
```

## MCAT: NEW

```{r, new_mcat, echo=FALSE}

# deidentfied raw
edu_db_con %>%
  deidentify_hashed(tbl_name = "new_mcat",
      "aamc_id", "appl_person_id") ->
  new_mcat_raw_deid 

new_mcat_raw_deid %>%
  write_to_database_single(edu_db_con, 
        add_tbl_prefix("new_mcat", status = "raw"))

# deidentfied clean
edu_db_con %>%
  clean_deidentified(tbl_name = "new_mcat", 
      min_year = 2016) ->
  new_mcat_clean_deid

new_mcat_clean_deid %>%
  write_to_database_single(edu_db_con, 
        add_tbl_prefix("new_mcat", status = "clean"))
  
# write data to file
new_mcat_raw_deid %>%
 write_to_file(deidentified_output, "new_mcat_raw_deidentified.csv")  
  
new_mcat_clean_deid %>%
 write_to_file(deidentified_output, "new_mcat_clean_deidentified.csv")
```

## Parent/Guardian

```{r, parent_guardian, echo=FALSE}

# deidentfied raw
edu_db_con %>%
  deidentify_hashed(tbl_name = "parent_guardian",
      "aamc_id", "appl_person_id", "living_ind", "name") ->
  parents_raw_deid 

parents_raw_deid %>%
  write_to_database_single(edu_db_con, 
        add_tbl_prefix("parent_guardian", status = "raw"))

# deidentfied clean
edu_db_con %>%
  clean_deidentified(tbl_name = "parent_guardian") ->
  parents_clean_deid

parents_clean_deid %>%
  write_to_database_single(edu_db_con, 
        add_tbl_prefix("parents", status = "clean"))

# write data to file
parents_raw_deid %>%
 write_to_file(deidentified_output, "parents_raw_deidentified.csv")  
  
parents_clean_deid %>%
 write_to_file(deidentified_output, "parents_clean_deidentified.csv")
```


```{r}
disconnect_all()
```
