---
title: "Generate grades-based features"
author: "Jacqueline Gutman, Suvam Paul"
date: 'Last updated: `r format(Sys.Date(), "%B %d, %Y") ` '
output:
  html_document:
    toc: yes
    toc_depth: '4'
  html_notebook:
    highlight: tango
    theme: cosmo
    toc: yes
    toc_depth: 4
---

# Setup
## Load packages
## Read in database credentials and open connection

```{r setup, message=FALSE, echo = FALSE}
knitr::read_chunk("setup_notebook.R")
```

```{r setup_notebook}
```

```{r show_pkgs, echo = FALSE}
print_loaded_pkgs()
```

# Generate grades features from deidentified clean

```{r}
get_tbls_by_pattern(edu_db_con, "deidentified\\Wclean\\Wgrades") %>%
  bind_rows() %>%
  filter(not(is_in(aca_status_desc, c("High School", "Graduate")))) -> 
  grades_input
```

```{r}
count_grades <- function(df) {
  df %>%
    group_by(study_id, appl_year) %>%
    summarize(a_counts = sum(amcas_grade_cd %in% c("A", "A-"), na.rm = TRUE),
            b_counts = sum(amcas_grade_cd %in% c("B", "B+", "B-", "AB"), na.rm = TRUE),
            c_counts = sum(amcas_grade_cd %in% c("C", "C+", "C-", "BC"), na.rm = TRUE),
            d_counts = sum(amcas_grade_cd %in% c("D", "D+", "D-", "CD", "DE"), na.rm = TRUE),
            f_counts = sum(amcas_grade_cd == "F", na.rm = TRUE)) %>%
    replace_na(list(a_counts = 0L, b_counts = 0L, c_counts = 0L, d_counts = 0L, f_counts = 0L))
}

bcpm_grade_counts <- grades_input %>%
  filter(bcpm_ind == 1) %>%
  count_grades() %>%
  rename_if(is.integer, funs(paste0("bcpm_", .)))
```

```{r}
grades_input %>%
  filter(bcpm_ind == 1) %>%
  group_by(class_cd) %>%
  nest() -> nested_science

nested_science %<>%
  mutate(features = map(data, count_grades)) %>%
  mutate(features = map2(features, class_cd, 
          function(df, name) rename_if(df, is.integer, funs(paste(tolower(name), ., sep = "_"))))) 
```

```{r}
nested_science %>% 
  use_series(features) %>%
  purrr::reduce(., left_join, by = c("study_id", "appl_year"), .init = bcpm_grade_counts) -> 
  all_grade_counts
```

```{r}
"grades" %>%
  add_tbl_prefix(status = "generated") %>%
  write_to_database_single(all_grade_counts, edu_db_con, .)
```

```{r}
disconnect_all()
```

