---
title: "Create feature version of GPA dataset"
author: "Suvam Paul"
date: 'Last updated: `r format(Sys.Date(), "%B %d, %Y") ` '
output:
  html_notebook:
    highlight: tango
    theme: cosmo
    toc: yes
    toc_depth: 4
  html_document:
    toc: yes
    toc_depth: '4'
---

# Setup
## Load packages
## Read in database credentials and open connection

```{r setup, message=FALSE, echo = FALSE, purl = FALSE}
knitr::read_chunk("setup_notebook.R")
```

```{r setup_notebook, purl = FALSE}

```

```{r echo = FALSE, purl = FALSE}
print_loaded_pkgs()
```



```{r check_tables_in_database}

table_names <- dbListTables(edu_db_con) %>% print()

```


```{r get_gpa_dataset}

#get data
gpa <- dbUtilities::put_tbl_to_memory(edu_db_con, "deidentified$clean$gpa")

```




```{r drop_high_school}
#education levels
table(gpa$aca_status_desc)

#drop high school grades
gpa %>% filter(aca_status_desc != "High School") -> gpa

```




```{r get_rid_of_unnecessary_columns}

gpa %>% select(-supp_hours_failed, -supp_hours_passed, -supp_hours_ap, -supp_hours_clep) -> gpa

```



```{r useful_rename_function}

find_and_replace <- function(dat_tbl, pattern, val) {
  dat_tbl %>% 
    names(.) %>% 
    stringr::str_replace_all(., pattern, map_chr(names(dat_tbl), function(x) {paste(x, val, sep = "_") })) 

}

```


```{r cumulative_gpa}

gpa_cumulative <- gpa %>% select(-ao_gpa, -ao_hours, -total_hours) %>% 
  filter(aca_status_desc == "Cumulative") 

names(gpa_cumulative) <- find_and_replace(gpa_cumulative, "bcpm_gpa|total_gpa|bcpm_hours", "cumulative")

gpa_cumulative <- gpa_cumulative %>% select(-aca_status_desc)

```


```{r post_bac}

gpa_post_bac <- gpa %>% select(-ao_gpa, -ao_hours) %>%  
  filter(aca_status_desc == "Postbaccalaureate Undergraduate")
names(gpa_post_bac) <- find_and_replace(gpa_post_bac, "bcpm_gpa|total_gpa|bcpm_hours|total_hours", "postbac")

gpa_post_bac <- gpa_post_bac %>% select(-aca_status_desc)

```


```{r attended_grad_schools}

gpa_grad <- gpa %>% 
  select(study_id, appl_year, aca_status_desc, total_hours) %>%  
  filter(aca_status_desc == "Graduate")  

names(gpa_grad) <- find_and_replace(gpa_grad, "total_hours", "grad")

gpa_grad <- gpa_grad %>% select(-aca_status_desc)
  
```


```{r total_and_science_gpa_trend}


#total gpa
total_gpa_trend <- gpa %>% 
  filter(aca_status_desc == "Freshman" | aca_status_desc == "Sophomore" | aca_status_desc == "Junior" | aca_status_desc == "Senior") %>%
  select(study_id, appl_year, aca_status_desc, total_gpa) %>% 
  spread(aca_status_desc, total_gpa) %>% 
  mutate(total_gpa_soph_higher = as.numeric(Sophomore > Freshman),
         total_gpa_juni_higher = as.numeric(Junior > Freshman),
         total_gpa_seni_higher = as.numeric(Senior > Junior)) %>% 
  select(-Freshman, -Sophomore, -Junior, -Senior) 
 

#science gpa
bcpm_gpa_trend <- gpa %>% 
  filter(aca_status_desc == "Freshman" | aca_status_desc == "Sophomore" | aca_status_desc == "Junior" | aca_status_desc == "Senior") %>%
  select(study_id, appl_year, aca_status_desc, bcpm_gpa) %>% 
  spread(aca_status_desc, bcpm_gpa) %>% 
  mutate(bcpm_gpa_soph_higher = as.numeric(Sophomore > Freshman),
         bcpm_gpa_juni_higher = as.numeric(Junior > Freshman),
         bcpm_gpa_seni_higher = as.numeric(Senior > Junior)) %>% 
  select(-Freshman, -Sophomore, -Junior, -Senior) 


```




```{r gpa_ready}

gpa_generated <- gpa_cumulative %>% 
  left_join(.,gpa_post_bac, by =c("study_id", "appl_year")) %>% 
  left_join(.,gpa_grad, by = c("study_id", "appl_year")) %>% 
  left_join(.,total_gpa_trend, by = c("study_id", "appl_year")) %>% 
  left_join(., bcpm_gpa_trend, by = c("study_id", "appl_year"))

```


```{r}
gpa_generated <- gpa_generated %>% 
  mutate(did_postbac = total_hours_postbac >= 12, 
         attended_grad_school = total_hours_grad >= 12) %>%
  replace_na(list(did_postbac = 0, attended_grad_school = 0, 
                  bcpm_hours_postbac = 0)) %>% 
  select(-total_hours_grad, -total_hours_postbac)


```


```{r put_tbl_to_database}

add_tbl_prefix("gpa", id = "deidentified", status = "generated") %>%
               write_to_database_single(gpa_generated, edu_db_con, tbl_name = .)

```

