---
title: "Prepare clean tables with basic cleaning and filtering"
subtitle: "Clean schema in preparation for ready-for-analysis stage"
author: "Jacqueline Gutman, Suvam Paul"
date: 'Last updated: `r format(Sys.Date(), "%B %d, %Y") ` '
output:
  html_document:
    toc: yes
    toc_depth: '4'
  html_notebook:
    highlight: tango
    theme: cosmo
    toc: yes
    toc_depth: 4
---

# Setup
## Load packages
## Read in database credentials and open connection

```{r setup, message=FALSE, echo = FALSE}
knitr::read_chunk("setup_notebook.R")
```

```{r setup_notebook}
```

```{r show_pkgs, echo = FALSE}
print_loaded_pkgs()
```

## Optionally write all deidentified data to text files

```{r deid_path}
write_deidentified_to_file = FALSE
deidentified_output <- "/Volumes/IIME/EDS/data/admissions/data_for_itai/"
```

```{r query_app_year}
query_rename_col <- "alter table ${tbl_name} change ${old_name} ${new_name} DOUBLE;"
tbl_names <- get_tbl_names_by_stage(edu_db_con, "deidentified", "raw")

tbl_names %>%
  find_tbls_with_col("app_year", edu_db_con) %>%
  map_lgl(function(tbl_name) interpolate_and_execute(query_rename_col, edu_db_con,
          commit = TRUE, tbl_name = tbl_name,                               
           old_name = "app_year", new_name = "appl_year"))
```

```{r get_edudw_deidentified}
pattern <- "^deidentified\\Wraw\\W[[:alpha:]].*[[:alpha:]]$"
# pattern <- "^deidentified\\Wraw\\W(grades|gpa|old_mcat)"

edu_db_con %>%
  get_tbls_by_pattern(pattern, in_memory = FALSE) -> 
  edudw_deidentified

edudw_deidentified %<>%
  names() %>%
  add_tbl_prefix() %>%
  set_names(edudw_deidentified, .) ->
  edudw_deidentified
```

```{r, eval = FALSE}
filter_last_app_only <- function (df_list, min_year, max_year) 
{
    df_list %>% 
        map(function(df) filter(df, appl_year >= min_year, 
                                    appl_year <= max_year)) %>% 
        map_if(function(df) not(tibble::is_tibble(df)), collect, n = Inf) %>% 
        map(function(df) group_by(df, study_id)) %>% 
        map(function(df) filter(df, appl_year == max(appl_year)))
}
```


```{r filter_edudw}
edudw_deidentified %<>%
  filter_first_app_only(min_year = 2013, max_year = 2017) %>%
  #filter_last_app_only(min_year = 2006, max_year = 2017) %>% 
  map(drop_empty_cols)
```

```{r edudw_mmi_fix}
edudw_deidentified$`deidentified$clean$mmi_scores` %<>%
  select(-mmi_question_id, -code) %>%
  mutate(interviewer_type = str_replace(interviewer_type, "Interviewer ", "")) %>%
  mutate(interviewer_type = as.integer(interviewer_type))
```

```{r edudw_exp_fix}
edudw_deidentified$`deidentified$clean$experiences` %<>%
  replace_na(list(first_total_hrs = 0,
                  second_total_hrs = 0,
                  third_total_hrs = 0,
                  fourth_total_hrs = 0)) %>%
  mutate(total_hrs = first_total_hrs + 
                     second_total_hrs +
                     third_total_hrs + 
                     fourth_total_hrs)
```

```{r edudw_old_mcat_fix}
edudw_deidentified$`deidentified$clean$old_mcat` %<>%
  set_names(str_replace_all(colnames(.), "_high", "")) %>%
  mutate(combined_score = vr_score + ps_score + bs_score)
```

```{r edudw_write}
edudw_deidentified %>%
  write_to_database(edu_db_con)
```

```{r edudw_write_file}
if (write_deidentified_to_file) {
  names(edudw_deidentified) %>%
    get_tbl_suffix() %>%
    paste("clean", "deidentified.csv", sep = "_") ->
    filenames

  edudw_deidentified %>%
    map2(filenames, function(df, name) write_to_file(df, deidentified_output, name))
}
```

## Add clean for admissions pile of data

```{r set_pattern_cols}
pattern <- "^deidentified\\Wraw\\W\\d{4}.*[[:alpha:]]$"

tracking_columns <- c("appl_submit_date",
                      "appl_complete_date",
                      "screening_complete_date",
                      "interview_invite_date",
                      "interview_schedule_date",
                      "interview_day",
                      "interview_complete_date",
                      "committee_date",
                      "offer_date",
                      "accept_date")
```

```{r get_app_data}
edu_db_con %>%
  get_tbls_by_pattern(pattern) -> 
  app_data_deidentified

app_data_deidentified %<>%
  names() %>%
  add_tbl_prefix() %>%
  set_names(app_data_deidentified, .)
```

```{r clean_app_data}
app_data_deidentified %>% 
  names() %>% 
  str_detect("201[3-7]") %>%
  magrittr::extract(app_data_deidentified, .) %>%
  do.call(bind_rows, .) %>%
  select(study_id, appl_year, one_of(tracking_columns), everything()) ->
  applicant_data
  
```

```{r filter_applications}
filter_applications <- . %>%
  # filter out M.D./Ph.D. applicants, special programs (i.e. linkages), and 
  # deferred applicants from previous years
  filter(appl_type_desc %in% c("Regular M.D.", "Combined  Medical Degree/Graduate")) %>%
  filter(!str_detect(status, "M\\w{2}")) %>%
  filter(!is.na(appl_submit_date) & !is.na(appl_complete_date))

applicant_data %<>% 
  filter_applications() %>% 
  drop_empty_cols() %>%
  select(-mstp, -mstp_to_md)
```

```{r fix_screener_score}
split_screener_score <- . %>% 
  mutate(screener_a_b = recode(scr_dec, 
          `2` = "1_1", `3` = "1_2", `4` = "4", `5` = "2_3", `6` = "3_3"),
        screener_a_b = if_else(scr_dec == 4, 
                       if_else(screener_sd == 0, "2_2", "1_3"), 
                       screener_a_b)) %>%
  separate(screener_a_b, c("screener_a", "screener_b")) %>%
  mutate(screener_a = int(screener_a),
         screener_b = int(screener_b),
         screener_total = int(screener_total))

applicant_data %<>%
  split_screener_score() %>%
  select(-screener_sd, -committee_sd) %>%
  rename(screener_total = scr_dec)
```

```{r add_indicator_cols}
applicant_data %<>%
  mutate(is_faculty_screened = !is.na(screening_complete_date),
         is_invited_interview = !is.na(interview_invite_date),
         is_interviewed = !is.na(interview_day),
         is_committee_reviewed = !is.na(committee_date),
         is_offered_admission = !is.na(offer_date))
```

```{r write_apps}
tbl_name <- "all_applicants" %>%
  add_tbl_prefix()

applicant_data %>%
  write_to_database_single(edu_db_con, tbl_name)
```

```{r write_apps_to_file}
if (write_deidentified_to_file) {
  applicant_data %>%
  write_to_file(deidentified_output, 
                  "admissions_all_applicants_deidentified_clean.csv")
}
```

```{r disconnect}
disconnect_all()
```
