tbl_model_data="aoa_admissions
aoa_admissions_inschool
residency_noncompete_admit
residency_noncompete_admit_inschool
residency_top25_admissions
residency_top25_admissions_inschool
screener_scores_admissions
worry_score_admissions
"

source activate edu_analytics
for tbl_name in $tbl_model_data
do
  python run_and_save_model.py --tbl $tbl_name
done
