tbl_model_data="aoa_admissions
aoa_admissions_inschool
residency_noncompete_admissions
residency_noncompete_admissions_inschool
residency_top_25_admissions
residency_top_25_admissions_inschool
screener_scores_admissions
worry_score_admissions
"

for tbl_name in $tbl_model_data
do
  python run_and_save_model.py --tbl $tbl_name
done
