---
title: "Upload deidentified outcomes data and new features"
author: "Jacqueline Gutman, Suvam Paul"
date: 'Last updated: `r format(Sys.Date(), "%B %d, %Y") ` '
output:
  html_document:
    toc: yes
    toc_depth: '4'
  html_notebook:
    highlight: tango
    theme: cosmo
    toc: yes
    toc_depth: 4
---

# Setup
## Load packages
## Read in database credentials and open connection

```{r setup, message=FALSE, echo = FALSE}
knitr::read_chunk("setup_notebook.R")
```

```{r setup_notebook}
```

```{r show_pkgs, echo = FALSE}
print_loaded_pkgs()
```

# Upload deidentified outcomes from flat text file

```{r data_dirs}
parent_path <- "/Volumes/IIME/EDS/data/admissions"
(data_dirs <- list.dirs(parent_path, full.names = TRUE, recursive = FALSE))
```

```{r}
data_dirs %>%
  str_detect("outcome_data") %>%
  magrittr::extract(data_dirs, .) %>%
  list.files(full.names = TRUE) -> outcome_data
```

```{r}
outcome_data %<>%
  str_detect("version_4") %>%
  magrittr::extract(outcome_data, .) %>%
  fread(na.strings = "NULL")
```

# Rename raw identified outcomes table from sql dump

```{r, eval = FALSE}
outcomes_dump_path <- file.path(parent_path, "outcome_data", "study_fact_application_v5.sql") %>%
  list(dump_path = .)
credentials <- read_lines(file.path(credentials_path, ".my.cnf"), n_max = 5, skip = 1)

credentials %<>%
  str_split(pattern = " = ") %>%
  transpose() %>%
  {set_names(.[[2]], .[[1]])} %>%
  append(outcomes_dump_path)

"mysql --user=${user} --password=${password} --host ${host} --port ${port} ${database} < ${dump_path}" %>%
  str_interp(credentials) %>%
  system()

rm(credentials)
```

```{r, eval = FALSE}

drop_tbl <- "drop table if exists ${new_name};"
query_rename <- "rename table ${old_name} to ${new_name};"
tbl_name <- "study_fact_application"

interpolate_and_execute(drop_tbl, edu_db_con, commit = TRUE,
                         new_name = add_tbl_prefix(tbl_name, id = "identified", status = "raw"))

interpolate_and_execute(query_rename, edu_db_con, commit = TRUE,
                         old_name = tbl_name,
                         new_name = add_tbl_prefix(tbl_name, id = "identified", status = "raw"))

```

```{r}
outcome_v5_cols <- c("study_id", "appl_year", "parent_edu_score",
  "median_income_zipcode", "worry_score_school_outcomes")
# select columns as features/outcomes and add in exp_* columns

study_fact_application <- put_tbl_to_memory(edu_db_con,
                          add_tbl_prefix(tbl_name, id = "identified", status = "raw")) %>%
  select(one_of(outcome_v5_cols), starts_with("exp_"))
```




```{r}
outcome_data %<>%
  left_join(study_fact_application, by = c("study_id", "appl_year"))
```

```{r}
outcome_tbl_name <- "outcomes_plus_features" %>%
  add_tbl_prefix(status = "outcome")

outcome_data %>%
  write_to_database_single(edu_db_con, outcome_tbl_name)
```



# Pull out outcomes and features from outcome data

```{r}
# Remove from all outcome data students in MD/PhD program
# Most outcomes will be delayed several years
outcome_inc_md_phd <- outcome_data

outcome_data %<>%
  filter(program_name != 'Combined Medical Degree/Ph.D')
```


```{r}
filter_valid_years <- function(outcome_name, data, year_range) {
  outcome <- outcome_name[1]
  
  data %>%
    select(study_id, appl_year, one_of(outcome_name)) %>%
    filter(appl_year >= year_range[[outcome]]$min_year,
          appl_year <= year_range[[outcome]]$max_year)
}

get_outcome_valid_years <- function(outcome_name, data, year_range) {
   filter_valid_years(outcome_name, data, year_range) %>%
    set_names(c(colnames(.)[-3], "outcome"))
}
```

```{r}
outcome_year_range <- yaml::yaml.load_file("outcomes.yaml")
```

```{r}
outcomes <- c("aoa")

outcomes %>%
  map(function (outcome) get_outcome_valid_years(outcome, outcome_data, outcome_year_range)) %>%
  map(function(df) replace_na(df, list(outcome = 0))) %>%
  map2_lgl(outcomes, function (df, outcome) write_to_database_single(
                                        df, edu_db_con, add_tbl_prefix(outcome, status = "outcome")))
```

```{r}
years <- outcome_year_range$residency_top_25_school

outcome_inc_md_phd %>% 
  select(study_id, appl_year, residency_top_25_school, residency_program) %>% 
  filter(appl_year >= years$min_year, appl_year <= years$max_year) %>% 
  filter(!is.na(residency_top_25_school)) %>%
  mutate(outcome = if_else(residency_program == "NYU SCHOOL OF MEDICINE", 
                           2L, residency_top_25_school)) -> outcome_top_25

outcome_top_25 %>%
  select(-residency_program, -residency_top_25_school) %>%
  write_to_database_single(edu_db_con, 
                           add_tbl_prefix("residency_top25", status = "outcome"))
```

```{r, eval = FALSE}
outcomes <- c("step1_score", "step2_score")
# if step 1/2 score is missing: no prediction, remove from outcome data
# if step 1/2 score is in bottom 25% percentile, outcome = 0
# if step 1/2 score is in middle 25%-75% percentile, outcome = 1
# if step 1/2 score is in top 75% percentile, outcome = 2

outcomes %>%
  map(function (outcome) get_outcome_valid_years(outcome, outcome_data, outcome_year_range)) %>%
  map(function (df) filter(df, !is.na(outcome))) %>%
  map(function(df) mutate(df, percentile = percent_rank(outcome))) %>%
  map(function(df) mutate(df, outcome = if_else(percentile <= .25, 0L,
                                        if_else(percentile <= .75, 1L, 2L)))) %>%
  map(function(df) select(df, -percentile)) %>%
  map2_lgl(outcomes, function (df, outcome) write_to_database_single(
                                        df, edu_db_con, add_tbl_prefix(outcome, status = "outcome")))
```

```{r}
years <- outcome_year_range$residency_top_25_school

outcome_inc_md_phd %>% 
  select(study_id, appl_year, residency_top_25_school, residency_difficulty) %>%
  filter(appl_year >= years$min_year, appl_year <= years$max_year) %>%
  filter(!is.na(residency_top_25_school)) %>% 
  filter((residency_top_25_school == 1) | !is.na(residency_difficulty)) %>%
  mutate(outcome = if_else(residency_top_25_school == 0 & residency_difficulty < 0.6, 1, 0)) -> outcome_non_compete

outcome_non_compete %>%
  select(-residency_difficulty, -residency_top_25_school) %>%
  write_to_database_single(edu_db_con, 
                           add_tbl_prefix("residency_noncompete", status = "outcome"))
```


```{r}

outcomes <- c("worry_score_school_outcomes")

outcomes %>%
  map(function (outcome) get_outcome_valid_years(outcome, outcome_inc_md_phd, outcome_year_range)) %>%
  map(function(df) mutate(df, outcome = if_else(outcome > 0, 1, 0))) %>%
  map2_lgl(outcomes, function (df, outcome) write_to_database_single(
                                        df, edu_db_con, add_tbl_prefix(outcome, status = "outcome")))
  
```


```{r}
outcome_v4_cols <- c("gender", "age_at_application", "college_top_25",
                      "is_disadvantaged", "urm", "advanced_degree",
                      "race_text", "total_accepted")
outcome_v5_cols <- c("study_id", "appl_year", "parent_edu_score", "median_income_zipcode")

exp_list <- outcome_inc_md_phd %>% select(starts_with("exp")) %>% colnames()
exp_list <- rep(0, length(exp_list)) %>% set_names(exp_list) %>% as.list()

outcome_inc_md_phd %>%
  select(one_of(outcome_v5_cols), one_of(outcome_v4_cols), starts_with("exp_")) %>%
  rename(race = race_text, num_schools_accepted_to = total_accepted) %>%
  replace_na(exp_list) %>%
  write_to_database_single(edu_db_con, add_tbl_prefix("other_features", status = "generated"))
```

```{r}
in_school_columns <- c("clerkship_honors_count",
                       "clerkship_pass_count", 
                       "course_clerkships_failed_count",
                       "shelf_exam_below65_count", 
                       "shelf_exam_above90_count", 
                       "school_exam_below65_count",
                       "school_exam_above90_count")

outcome_inc_md_phd %>%
  select(study_id, appl_year, one_of(in_school_columns)) -> in_school_data

replace_invalid_year <- function(data, outcome_name, year_range) {
  dots <- lazyeval::interp(~ if_else(
      (appl_year >= min_year) &
      (appl_year <= max_year),
    col, NA_integer_),
    min_year = year_range[[outcome_name]]$min_year,
    max_year = year_range[[outcome_name]]$max_year,
    col = as.name(outcome_name))
    
  data %>%
    mutate_(.dots = set_names(list(dots), outcome_name))
}

reduce(in_school_columns, replace_invalid_year, 
       year_range = outcome_year_range,
      .init = in_school_data) -> in_school_data
```

```{r}
in_school_data %>%
  write_to_database_single(edu_db_con, add_tbl_prefix("in_school_performance", status = "generated"))
```

