---
title: "Add hashed study ID for deidentification"
author: "Jacqueline Gutman, Suvam Paul"
date: 'Last updated: `r format(Sys.Date(), "%B %d, %Y") ` '
output:
  html_notebook:
    highlight: tango
    theme: cosmo
    toc: yes
    toc_depth: 4
  html_document:
    toc: yes
    toc_depth: '4'
---

# Setup
## Load packages
## Read in database credentials and open connection

```{r setup, message=FALSE, echo = FALSE}
knitr::read_chunk("setup_notebook.R")
```

```{r setup_notebook}
```

```{r show_pkgs, echo = FALSE}
print_loaded_pkgs()
```

```{r get_tbls}
all_table_names <- dbListTables(edu_db_con)

get_tbl_names_by_stage(edu_db_con, "identified", "raw") -> raw_identified_tbls

get_tbl_names_by_stage(edu_db_con, "identified", "outcome") -> raw_identified_outcome_tbls
```

```{r amcas_aamc}
raw_identified_tbls %>%
  find_tbls_with_col("amcas_id", edu_db_con) %>%
  get_tbl_suffix() -> amcas_id_tbls

raw_identified_tbls %>%
  find_tbls_with_col("aamc_id", edu_db_con) %>%
  get_tbl_suffix() -> aamc_id_tbls
```

```{r hash_amcas, results='hide'}
interpolate_hash <- function(tbl_name, col_name, conn, status = "raw") {
  query_drop <- "drop table if exists `${hashed_tbl_name}`;"

  query_create <- "create table `${hashed_tbl_name}` as (
  select md5(${col_name}) as study_id, a.*
  from `${identified_tbl_name}` a);"

  hashed_tbl_name = add_tbl_prefix(tbl_name,
                id = "hashed", status = status)
  identified_tbl_name = add_tbl_prefix(tbl_name,
                id = "identified", status = status)

  query_drop %>%
    interpolate_and_execute(., conn, commit = TRUE,
                            hashed_tbl_name = hashed_tbl_name)

  query_create %>%
    interpolate_and_execute(., conn, commit = TRUE,
          hashed_tbl_name = hashed_tbl_name,
          col_name = col_name,
          identified_tbl_name = identified_tbl_name)
}

map(amcas_id_tbls, interpolate_hash,
    col_name = "amcas_id", conn = edu_db_con) %>%
  flatten_lgl()
```

```{r hash_aamc, results='hide'}
map(aamc_id_tbls, interpolate_hash,
    col_name = "aamc_id", conn = edu_db_con) %>%
  flatten_lgl()

map(raw_identified_outcome_tbls, interpolate_hash,
    col_name = "aamc_id", status = "outcome", conn = edu_db_con) %>%
  flatten_lgl()
```

```{r disconnect}
disconnect_all()
```
